### ISSUE TITLE
书中关于CANDIDATE也拥有选举超时的任务

### ISSUE THREAD

**Issue by jzdayz** [xnnyygn/xraft#17]
为什么CANDIDATE也会拥有选举超时的任务？是为了防止整个请求投票的过程时间太长吗？
如果请求投票迟迟不受到响应，就会将自己的任期+1，然后进行新一轮的投票？

**Comment by jzdayz** [comment]
in.xnnyygn.xraft.core.node.NodeImpl#doProcessElectionTimeout 这个方法中

295行  role.cancelTimeoutOrTask();

这行代码为什么要取消任务
走到这里的话，当前的role就是follower或者Candidate，也就是说取消现在当前执行的方法？

**Comment by jzdayz** [comment]
> in.xnnyygn.xraft.core.node.NodeImpl#doProcessElectionTimeout 这个方法中
> 
> 295行 role.cancelTimeoutOrTask();
> 
> 这行代码为什么要取消任务
> 走到这里的话，当前的role就是follower或者Candidate，也就是说取消现在当前执行的方法？

并且走到295行，相当于此时的任务已经走完了(提交到了taskExecutor)，这个cancel还有意义吗

**Comment by xnnyygn** [comment]
这是Raft算法的要求。Candidate状态下存在收不到足够票数的情况，此时Candidate只能选择重新开始选举。

role.cancelTimeoutOrTasks() 确实可能不是必要的，现在主要是测试里面使用。
