### ISSUE TITLE
如果能按照章节存放源代码就更好了。

### ISSUE THREAD

**Issue by better-maksim** [xnnyygn/xraft#8]
目前这本书给我感觉最大的缺点就是代码太混乱了，书中代码示例中有大量文中之前没有提到过的方法，如果出第二版的话，希望能够修正，源代码按照章节存放就更好了。

**Comment by xnnyygn** [comment]
谢谢。现在这个repo是最终成品。如果针对书的话，按照章节分开放比较好。
